name: Fetch Data Cron Job

on:
  push:
    branches:
      - main # Ganti dengan branch yang relevan
  schedule:
    - cron: '* * * * *' # Setiap menit
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Update ke versi terbaru

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Update ke versi terbaru
      with:
        node-version: '20' # Gunakan versi terbaru Node.js

    - name: Install dependencies
      run: npm install

    - name: Run fetch data script
      run: node src/index.js
