name: Fetch Data Cron Job

on:
  schedule:
    - cron: '* * * * *' # Setiap menit
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Atur versi Node.js sesuai kebutuhan

    - name: Install dependencies
      run: npm install

    - name: Run fetch data script
      run: node src/index.js
